### ISSUE TITLE
[MAINTENANCE] Is this project and/or maintainer still active?

### ISSUE THREAD

**Issue by drakeerv** [GladiusSlicer/GladiusSlicer#6]
Hope you are doing ok @mrhatman

**Comment by GodGotzi** [comment]
some comments and docs in code would be nice, to be able to work on this. Maybe we need to switch maintainer

**Comment by mrhatman** [comment]
Yes, I am doing fine. The code functions and It works for my use cases. 

I will likely pick it up at some point and add features.

I can add in some docs, I should have done that a while ago.

The project is always available to be forked and worked on.
