### ISSUE TITLE
[BUG] You implement PolygonOperations for Polygon, there you call self.union for the function xor_with(&self, other: Self)?

### ISSUE THREAD

**Issue by GodGotzi** [GladiusSlicer/GladiusSlicer#7]
## Description

Is that a mistake or on purpose?
![image](https://github.com/user-attachments/assets/7ab7aa97-980c-4ae6-8c78-1bd7457b1406)

**Comment by GodGotzi** [comment]
I think a mistake (you didn't even use xor_with). I got confused a little bit.

**Comment by mrhatman** [comment]
Yes this is a bug
xor_with is currently not
It has been fixed already in the dev branch. 

I am currently going through the code, speeding things up, improving documentation, and fixing issues. 

I should be releasing a new release in the next few days.
